#! /bin/sh

#chkconfig:345 60 60
#description:Ceict server setup for fist boot

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

start()
{
	ret=0
	DEFUSER="pic"
	DEFPASS="2O1lCeIcT"
	ls /etc/rc3.d/ | grep "K[0-9]\{1,\}mysqld" > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		/sbin/chkconfig --level 345 mysqld on
		/sbin/service mysqld start > /dev/null 2>&1
		mysqladmin -u root password '2011ceict'
		mysql -uroot -p2011ceict -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY '2011ceict' WITH GRANT OPTION;"
		mysql -uroot -p2011ceict -e "FLUSH PRIVILEGES;"
		mysql -uroot -p2011ceict -e "create database ims;"

		if [ -f /usr/share/ceict-webapp-data/cmt/config.properties ]; then
			sed -i 's/\/etc\/asterisk/\/etc\/ceictims/g' /usr/share/ceict-webapp-data/cmt/config.properties
			sed -i 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/localhost/g' /usr/share/ceict-webapp-data/cmt/config.properties
			sed -i 's/ems3/ims/g' /usr/share/ceict-webapp-data/cmt/config.properties
		fi
		# Setting ftp
		/sbin/chkconfig --level 345 vsftpd on
		/sbin/service vsftpd start > /dev/null 2>&1
		id $DEFUSER
		if [ $? -ne 0 ]; then
			/usr/sbin/adduser -d /opt/pic -g ftp -s /sbin/nologin $DEFUSER
			echo "$DEFPASS" | passwd --stdin $DEFUSER
		fi

	else
		echo "Password configuration already present."
		ret=1
	fi

	[ $ret -eq 0 -a -d /var/lock/subsys ] && touch /var/lock/subsys/ceict-firstboot
}

stop()
{
	[ -f "/var/lock/subsys/ceict-firstboot" ] && rm -f /var/lock/subsys/ceict-firstboot
	return 0
}

case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	*)
		echo $"Usage: $0 {start|stop}"
		exit 1
esac


